server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: authentication-service
    server: http://localhost:${server.port}
    title: Authentication service
    version: 1.0.0

jwt:
  expiryMinutes: 30
  expiryDay: 14
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID:793208159346-4ucpps18skm5kcq7ppp4uke1ci38l85q.apps.googleusercontent.com}
  github:
    client-id: ${GITHUB_CLIENT_ID:Ov23liwCFxVfCS2HTgbN}
    client-secret: ${GITHUB_CLIENT_SECRET:7559c717069caeb3bae254ef5d174839dcd06071}
