-- 1. Create Enums if not exist
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender') THEN 
        CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER'); 
    END IF; 
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userstatus') THEN 
        CREATE TYPE userstatus AS ENUM ('ACTIVE', 'INACTIVE', 'LOCKED'); 
    END IF; 
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usertype') THEN 
        CREATE TYPE usertype AS ENUM ('USER', 'ADMIN', 'DRIVER'); 
    END IF; 
END $$;

-- 2. Create Tables
CREATE TABLE IF NOT EXISTS tbl_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS tbl_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username CHARACTER VARYING(255) UNIQUE,
    password CHARACTER VARYING(255),
    email CHARACTER VARYING(255),
    first_name CHARACTER VARYING(255),
    last_name CHARACTER VARYING(255),
    phone CHARACTER VARYING(255),
    date_of_birth DATE,
    gender GENDER,
    status USERSTATUS DEFAULT 'ACTIVE',
    type USERTYPE DEFAULT 'USER',
    is_two_factor_enabled BOOLEAN DEFAULT FALSE,
    secret CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS tbl_user_has_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES tbl_user(id),
    role_id BIGINT REFERENCES tbl_role(id)
);

CREATE TABLE IF NOT EXISTS tbl_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING(255) UNIQUE,
    description CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS tbl_role_has_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT REFERENCES tbl_role(id),
    permission_id BIGINT REFERENCES tbl_permission(id)
);

CREATE TABLE IF NOT EXISTS tbl_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING(255) UNIQUE,
    description CHARACTER VARYING(255),
    role_id BIGINT UNIQUE REFERENCES tbl_role(id)
);

CREATE TABLE IF NOT EXISTS tbl_group_has_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES tbl_group(id),
    user_id BIGINT REFERENCES tbl_user(id)
);

-- 3. Insert Default Data
-- Roles
INSERT INTO tbl_role (id, name) VALUES (1, 'USER'), (2, 'ADMIN'), (3, 'OWNER') 
ON CONFLICT (id) DO NOTHING;
SELECT setval('tbl_role_id_seq', (SELECT MAX(id) FROM tbl_role));

-- Users (Mật khẩu mặc định: admin123 cho admin/kinn, demo123 cho demo)
-- Admin
INSERT INTO tbl_user (id, username, password, email, first_name, last_name, status, type, is_two_factor_enabled) 
VALUES (2, 'admin', '$2a$10$0zfDuSov6Wv1QL88wTv.9enhPaJMdQd4RUdRqVN7AeURV3xPInoMC', 'admin@local', 'System', 'Admin', 'ACTIVE', 'ADMIN', false)
ON CONFLICT (id) DO NOTHING;

-- Kinn (Account riêng cho user)
INSERT INTO tbl_user (id, username, password, email, first_name, last_name, status, type, is_two_factor_enabled) 
VALUES (4, 'kinn', '$2a$10$0zfDuSov6Wv1QL88wTv.9enhPaJMdQd4RUdRqVN7AeURV3xPInoMC', 'kinn@logistic.vn', 'Truong', 'Kinn', 'ACTIVE', 'ADMIN', false)
ON CONFLICT (id) DO NOTHING;

-- Demo
INSERT INTO tbl_user (id, username, password, email, first_name, last_name, status, type, is_two_factor_enabled) 
VALUES (1, 'demo', '$2a$10$0zfDuSov6Wv1QL88wTv.9enhPaJMdQd4RUdRqVN7AeURV3xPInoMC', 'demo@local', 'Demo', 'User', 'ACTIVE', 'USER', false)
ON CONFLICT (id) DO NOTHING;

SELECT setval('tbl_user_id_seq', (SELECT MAX(id) FROM tbl_user));

-- Assign Roles
-- Admin has all roles
INSERT INTO tbl_user_has_role (user_id, role_id) VALUES (2, 1), (2, 2), (2, 3) ON CONFLICT DO NOTHING;
-- Kinn has all roles
INSERT INTO tbl_user_has_role (user_id, role_id) VALUES (4, 1), (4, 2), (4, 3) ON CONFLICT DO NOTHING;
-- Demo has USER role
INSERT INTO tbl_user_has_role (user_id, role_id) VALUES (1, 1) ON CONFLICT DO NOTHING;

SELECT setval('tbl_user_has_role_id_seq', (SELECT MAX(id) FROM tbl_user_has_role));
